[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "C7jvMC4XbWNnUbgtC4oogFQ25KTyRDVFdW82tAZmh6gu"

[programs.devnet]
vault = "C7jvMC4XbWNnUbgtC4oogFQ25KTyRDVFdW82tAZmh6gu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../../walets/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "../../walets/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
