[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "GAUiqjw3dS9pXPJydPG4jahZ7UrWEMp8BhhFkqh9H9cJ"

[programs.devnet]
vault = "GAUiqjw3dS9pXPJydPG4jahZ7UrWEMp8BhhFkqh9H9cJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../../wallets/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "../../wallets/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
